# Generated by Django 5.1.4 on 2024-12-10 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehousemgt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='warehousemgt.user')),
                ('postion', models.TextField()),
            ],
            bases=('warehousemgt.user',),
        ),
    ]
