# Generated by Django 5.1.4 on 2024-12-14 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehousemgt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='warehousemgt.customer'),
        ),
    ]
