# Generated by Django 5.1.4 on 2024-12-10 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehousemgt', '0003_document_alter_item_icon_alter_user_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='customers',
            field=models.ManyToManyField(blank=True, null=True, related_name='Items', to='warehousemgt.customer'),
        ),
        migrations.AlterField(
            model_name='item',
            name='sold_by',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='sold_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
