# Generated by Django 5.1.4 on 2024-12-10 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehousemgt', '0004_alter_item_customers_alter_item_sold_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='customers',
            field=models.ManyToManyField(blank=True, related_name='items', to='warehousemgt.customer'),
        ),
        migrations.AlterField(
            model_name='item',
            name='isAvailble',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='sold_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehousemgt.employee'),
        ),
    ]
